##
#################################################################################
##                                       
##  Copyright (c) 2021 phwang. All rights reserved.
##
#################################################################################
##

include ../Makefile.inc

MAIN_OBJS = main.o  

main.o: main.cpp 
	$(GPP) -c main.cpp


#all: $(MAIN_OBJS)

#cpp.o:
#	$(GPP) -c $< -o $@ -lpthread -ldl

clean: 
	$(RM) $(MAIN_OBJS)


