##
#################################################################################
##                                       
##  Copyright (c) 2021 phwang. All rights reserved.
##
#################################################################################
##

include ../Makefile.inc

OBJS = test_class.o

all: $(OBJS)
	$(GPP) -c $(OBJS)

clear: 
	rm *.o

