##
#################################################################################
##                                       
##  Copyright (c) 2021 phwang. All rights reserved.
##
#################################################################################
##

include ../Makefile.inc

sqlite3.o: sqlite3.c 
	$(GCC) sqlite3.c -c -lpthread -ldl

clear: 
	rm *.o

