##
#################################################################################
##                                       
##  Copyright (c) 2021 phwang. All rights reserved.
##
#################################################################################
##

include ../Makefile.inc

OBJS = root_class.o raw_api_class.o

all: $(OBJS)
	$(GPP) -c $(OBJS)

clear: 
	rm *.o

