##
#################################################################################
##                                       
##  Copyright (c) 2021 phwang. All rights reserved.
##
#################################################################################
##

all: sqlite3.c shell.c
	gcc sqlite3.c shell.c -o sqlite3 -lpthread -ldl

clear: 
	rm *.o

