##
#################################################################################
##                                       
##  Copyright (c) 2021 phwang. All rights reserved.
##
#################################################################################
##

include ../../Makefile.inc

OBJS = abend_class.o

abend_class.o:	abend_class.cpp abend_class.h
	$(GPP) -c abend_class.cpp

clear: 
	$(RM) $(OBJS)


